//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh
    {
        public Nullable<int> SoLuongSachTonToiThieuDeNhap { get; set; }
        public Nullable<int> SoLuongSachNhapToiThieuDeNhap { get; set; }
        public Nullable<int> TienToiDa { get; set; }
        public Nullable<int> SoLuongSachTonToiThieuSauKhiBan { get; set; }
        public Nullable<bool> TienThuLonHonNo { get; set; }
        public int id { get; set; }
    }
}
